### PR TITLE
KNF.

### PR DESCRIPTION
**Pull request by bentley**
Reduces the diff to OpenBSD by ~1000 lines.

I left lines with comments alone.

### CODE REVIEW

**Comment by mmcco** [comment]
This looks good to me. Thoughts?

**Comment by lichray** [comment]
👍

**Comment by mmcco** [comment]
Is there someone else who needs to ok these before they're merged?

**Comment by lichray** [comment]
Nope, just marking it so that I won't forget it.

**Comment by mmcco** [comment]
Nice. I'm going to submit a handful more in the next few days. OpenBSD is interested in reducing the diff between its vi and nvi2. We have some cleanup patches queued up that we'd like to share.

**Pull request closed without merging**
