### PR TITLE
missing header for timespec

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by lichray** [comment]
We include `#include <sys/time.h>` in every .c files who need it.  Please point me out which files need them (no matter how many they are) and I will add those.

**Comment by devnexen** [comment]
common/exf.h

**Comment by lichray** [comment]
Yes, I know, but if you look at `common/exf.h`, it also depends on all kinds of types `db.h` provides, but doesn't include any header.  It's just a nvi coding tradition... To include necessary headers only in .c files to avoid pollution.  Can you show me the build error you got?

**Comment by devnexen** [comment]
"field has incomplete type" basically.

**Comment by lichray** [comment]
I know that as well... I just want to know which .c file(s) included that common/exf.h and triggered this error.  If you don't mind, you can paste the full error message here; I can read that.

**Comment by devnexen** [comment]
Maybe including it into common/cut.c would fit better then ?

**Comment by lichray** [comment]
If
```
diff --git a/common/cut.c b/common/cut.c
index 7af4a1d..664036d 100644
--- a/common/cut.c
+++ b/common/cut.c
@@ -15,6 +15,7 @@ static const char sccsid[] = "$Id: cut.c,v 10.12 2012/02/11 15:52:33 zy Exp $";

 #include <sys/types.h>
 #include <sys/queue.h>
+#include <sys/time.h>

 #include <bitstring.h>
 #include <ctype.h>

```

eliminates your build error, I'll be glad to accept the change.

**Comment by devnexen** [comment]
Sure was needed in another place too afterwards.

**Comment by lichray** [comment]
It's ok, just point it out to me.  You can search for 'time.h' in the source tree to see how many files included them.

**Comment by devnexen** [comment]
I pushed another change which make things compilable now.

**Comment by lichray** [comment]
Thanks!

**Pull request closed without merging**
