### PR TITLE
Find db.h on macOS & Fix build error

### LINKED ISSUE #69: Build failure on macOS
Latest master fails to build on macOS.

Steps:
1. Run `cmake .`
2. Run `make`

Output:
```
Scanning dependencies of target regex
[  1%] Building C object CMakeFiles/regex.dir/Users/emirsari/Projeler/GitHub/nvi2/regex/regcomp.c.o
[  2%] Building C object CMakeFiles/regex.dir/Users/emirsari/Projeler/GitHub/nvi2/regex/regerror.c.o
[  3%] Building C object CMakeFiles/regex.dir/Users/emirsari/Projeler/GitHub/nvi2/regex/regexec.c.o
[  4%] Building C object CMakeFiles/regex.dir/Users/emirsari/Projeler/GitHub/nvi2/regex/regfree.c.o
[  5%] Linking C static library libregex.a
[  5%] Built target regex
[  6%] Generating /Users/emirsari/Projeler/GitHub/nvi2/ex/version.h
[  6%] Generating /Users/emirsari/Projeler/GitHub/nvi2/cl/extern.h
[  7%] Generating /Users/emirsari/Projeler/GitHub/nvi2/common/extern.h
[  8%] Generating /Users/emirsari/Projeler/GitHub/nvi2/ex/extern.h
[  9%] Generating /Users/emirsari/Projeler/GitHub/nvi2/vi/extern.h
[ 10%] Generating /Users/emirsari/Projeler/GitHub/nvi2/common/options_def.h
[ 10%] Generating /Users/emirsari/Projeler/GitHub/nvi2/ex/ex_def.h
Scanning dependencies of target nvi
[ 11%] Building C object CMakeFiles/nvi.dir/Users/emirsari/Projeler/GitHub/nvi2/cl/cl_funcs.c.o
In file included from /Users/emirsari/Projeler/GitHub/nvi2/cl/cl_funcs.c:32:
/Users/emirsari/Projeler/GitHub/nvi2/cl/../common/common.h:12:10: fatal error: '/usr/include/db.h'
      file not found
#include "/usr/include/db.h"    /* Only include db1. */
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/nvi.dir/Users/emirsari/Projeler/GitHub/nvi2/cl/cl_funcs.c.o] Error 1
make[1]: *** [CMakeFiles/nvi.dir/all] Error 2
make: *** [all] Error 2
```

ss

berkeley-db 18.1.32_1 is already installed on my system.

### PR DESCRIPTION
**Pull request by bitigchi**
Fixes #69. Sorry about the mess from my messages PR.

Ekran Resmi 2020-02-27 19 17 02

### CODE REVIEW

**Comment by lichray** [comment]
You are not using `find_path` correctly.  The path is now saved into a variable called `db.h`, and unused.  It works on your machine because this change is indifferent from reverting 8461afc, which is fine but may not work on older macOS.  What's your OSX version BTW?

**Comment by bitigchi** [comment]
@lichray, please let me know how the latest update looks. Feel free to point out any unpolished parts etc., would be greatly appreciated.

**Comment by lichray** [comment]
```diff
diff --git a/build/CMakeLists.txt b/build/CMakeLists.txt
index 606d290..a515c5e 100644
--- a/build/CMakeLists.txt
+++ b/build/CMakeLists.txt
@@ -90,6 +90,11 @@ endif(NOT RESOLV_IN_LIBC)

 include_directories(. ..)

+find_path(DB1_INCLUDE_DIR
+       NAMES db.h
+       PATHS /usr/include /usr/local/include /opt/include /opt/X11/include)
+include_directories(${DB1_INCLUDE_DIR})
+
 find_library(_curses_lib NAMES ncurses curses HINTS /usr/lib)
 find_library(_cursesw_lib NAMES ncursesw cursesw curses HINTS /usr/lib)
 mark_as_advanced(_curses_lib _cursesw_lib)
diff --git a/common/common.h b/common/common.h
index d4412de..0920c26 100644
--- a/common/common.h
+++ b/common/common.h
@@ -6,10 +6,10 @@
  *
  * See the LICENSE file for redistribution information.
  *
- *     $Id: common.h,v 10.23 2017/11/14 00:34:44 zy Exp $
+ *     $Id: common.h,v 10.24 2020/02/28 17:50:49 bitigchi Exp $
  */

-#include "/usr/include/db.h"   /* Only include db1. */
+#include <db.h>
 #include <regex.h>             /* May refer to the bundled regex. */

 /*
```
See if this works.

**Comment by bitigchi** [comment]
@lichray, it did not. I've tried this one before as well.

**Comment by lichray** [comment]
The effect of `CMAKE_REQUIRED_INCLUDES` is a mystery then.  I think we'd better to setup a CI (probably Cirrus) for this.

**Comment by bitigchi** [comment]
Asking out of ignorance -- it's my first time using it, isn't `CMAKE_REQUIRED_INCLUDES` is what's needed here? I thought it's doing what it's supposed to be doing.

**Comment by lichray** [comment]
> Asking out of ignorance -- it's my first time using it, isn't `CMAKE_REQUIRED_INCLUDES` is what's needed here? I thought it's doing what it's supposed to be doing.

It should have no effect to anything other than the `check_include_files`.  So to the build process, it should have no effect.  You can check the actual build commands before and after with `make VERBOSE=1`.  `include_directories` can filter out the path if it is compiler builtin path (in that case, no effect).  But if that causes the project not to build, I need to know why.

**Comment by bitigchi** [comment]
I understand now, thank you. If you need me to test anything, please let me know, I'll assist with pleasure.

**Comment by lichray** [comment]
Can you try this?  Write a file `a.c` with one line `#include <db.h>` in it, run `clang -E a.c` and find the actual path to 'db.h' to be included, then run `clang -E -I/usr/local/include a.c` and compare the results.

**Comment by bitigchi** [comment]
I diff'd them and both are exactly the same. Files respectively below.

[clang_output_dbh.txt](https://github.com/lichray/nvi2/files/4277078/clang_output_dbh.txt)

[clang_output_dbh_2.txt](https://github.com/lichray/nvi2/files/4277077/clang_output_dbh_2.txt)

**Comment by lichray** [comment]
Superseded by #89

**Pull request closed without merging**
