### PR TITLE
Provide Turkish messages

### PR DESCRIPTION
**Pull request by bitigchi**
This PR adds Turkish messages for nvi2.

I installed FreeBSD to try the messages in runtime, but I was unable to set it properly. All of my locale settings are `tr_TR.UTF-8`, and when I use `:set msgcat=/path/to/file`, I get "blah blah is not a message catalog". Anyone can walk me through this? Translations are pretty much accurate, but I'd definitely like to test them before it ships in a new version.

### CODE REVIEW

**Comment by lichray** [comment]
1. Can you rename the file to `tr_TR.UTF-8.base` and such?
2. It "works" on my box (but my terminal isn't utf-8 so I can't read; the program accepts this msgcat).  I ran `make` first under the `catalog` directory, and then did `:se msgcat=turkish`.

**Comment by bitigchi** [comment]
I was able to view messages by `msgcat` command now, thank you. However, I am still unable to display Latin extended characters like ğ, Ğ, ı, İ, ş, and Ş on default terminal under Virtualbox, no GUI installed.

I modified `/etc/login.conf`, `/etc/profile/`, `/etc/csh.login/` (tried with bash also) with the appropriate entries. I also modified `kern.vty` as per [this page](https://stackoverflow.com/questions/37967810/freebsd-is-set-to-utf-8-but-seems-to-display-in-ascii), but didn't work either.

When I set the encoding and locale as `tr_TR.UTF-8`, I get question marks. If I change it to `iso8859-9`, Turkish-specific characters are not displayed at all.

I have no trouble testing with a question mark, but a solution would be great in order to get it displayed right.

**Comment by rjc** [comment]
@bitigchi There are still some issues with [`vt(4)`](https://wiki.freebsd.org/Newcons). Are required fonts installed and configured?

**Comment by lichray** [comment]
Do they display with `cat`?  If yes, that's not font's problem.

**Comment by bitigchi** [comment]
@rjc, @lichray apparently it was font related after all. Installing terminus font and changing to it solved the problem.

VirtualBox_FreeBSD_27_02_2020_12_39_48

I will test this for a couple of days, and will let you know when it's good to go!

**Comment by bitigchi** [comment]
All good to go!

**Pull request merged**
